# Generated by Django 5.2.3 on 2025-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Preventive Care', 'Preventive Care'), ('Surgical Procedures', 'Surgical Procedures'), ('Dental Care', 'Dental Care'), ('Diagnostic Imaging', 'Diagnostic Imaging'), ('Emergency Services', 'Emergency Services'), ('Nutritional Counseling', 'Nutritional Counseling')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
