# Generated by Django 5.2.3 on 2025-06-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='vet',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vet',
            old_name='department',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='vet',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
