# Generated by Django 5.2.3 on 2025-06-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_description_vet_bio_rename_full_name_vet_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='preferred_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='preferred_time',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Preventive Care', 'Preventive Care'), ('Surgical Procedures', 'Surgical Procedures'), ('Dental Care', 'Dental Care'), ('Diagnostic Imaging', 'Diagnostic Imaging'), ('Emergency Services', 'Emergency Services'), ('Nutritional Counseling', 'Nutritional Counseling')], default='Preventive Care', max_length=40),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('preferred_date', 'preferred_time'), name='unique_preferred_slot'),
        ),
    ]
