# Generated by Django 5.2.3 on 2025-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_appointment_date_appointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Payment Amount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='Payment Status'),
        ),
    ]
