# Generated by Django 5.2.3 on 2025-07-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vetavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VetAvailability',
        ),
    ]
