# Generated by Django 5.2.3 on 2025-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_vetavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('other', 'Other')], max_length=20),
        ),
    ]
