# Generated by Django 5.2.3 on 2025-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_appointment_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=20),
        ),
    ]
