# Generated by Django 5.2.3 on 2025-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_appointment_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'completed')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
