# Generated by Django 5.2.3 on 2025-08-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet_age',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pet Age'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_weight',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pet Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
